version: "3.7"

services:
  task-4:
    build:
      context: .
    stdin_open: true
    tty: true
    working_dir: /usr/src/app
    networks:
      - cources-network
    ports:
      - 127.0.1.1:3000:3000
    volumes:
      - .:/usr/src/app
      - rubies:/opt/rubies
    depends_on:
      - db
      - arc
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://postgres:password@db/"
    entrypoint: /docker-entrypoint.sh
    command: "bin/startup"

  db:
    image: postgres:10-alpine
    networks:
      cources-network:
        aliases:
          - db
    volumes:
      - .docker/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
  arc:
    image: alpine:latest
    volumes:
      - rubies:/cont/rubies
      - .docker:/host/docker
    networks:
      - cources-network
    working_dir: /cont
    entrypoint: tar -czf /host/docker/current.tgz rubies/

  pghero:
    image: ankane/pghero
    depends_on:
      - db
    ports:
      - 127.0.1.1:8080:8080
    environment:
      DATABASE_URL: "postgres://postgres:password@db/task-4_development"
    networks:
      - cources-network

networks:
  cources-network:
    name: cources-network

volumes:
  rubies:
